# Generated by Django 4.2 on 2024-06-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Disabled', 'Disabled'), ('Rejected', 'Rejected'), ('In Review', 'In Review'), ('Live', 'Live')], default='Live', max_length=20),
        ),
    ]
