# Generated by Django 4.2 on 2024-06-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking_alter_hotel_description_staffonduty_roomtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Instagram',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Twitter',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='YouTube',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facebook',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
