# Generated by Django 4.2 on 2024-06-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_instagram_hotel_twitter_hotel_youtube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
