# Generated by Django 4.2 on 2024-06-20 14:44

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('hotel', '0005_hotel_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='Instagram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Twitter',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='YouTube',
            new_name='youtube',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tags',
        ),
        migrations.AddField(
            model_name='hotel',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
