# Generated by Django 4.2 on 2024-06-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_rename_instagram_hotel_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
