# Generated by Django 4.2 on 2024-07-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_booking_check_out_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookingID',
            new_name='booking_id',
        ),
    ]
