# Generated by Django 4.2 on 2024-07-03 14:26

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_rename_bookingid_booking_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('type', models.CharField(default='Percentage', max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('redemptions', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateTimeField()),
                ('couponId', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=50, prefix='', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='hotel.coupon'),
        ),
    ]
