# Generated by Django 4.2 on 2024-07-24 14:01

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_coupon_booking_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='successID',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz', blank=True, length=10, max_length=20, null=True, prefix='', unique=True),
        ),
    ]
